In [1]:
!pip install pandas
!pip install openpyxl

import pandas as pd
import openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\12401390\appdata\roaming\python\python312\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\12401390\appdata\roaming\python\python312\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in c:\users\12401390\appdata\roaming\python\python312\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\program files\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\12401390\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\12401390\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
caminho = r"H:\Materias - Escola\PYTHON\Atividade4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [26]:
arquivo_bruto = pd.read_excel(caminho, header=2)

In [27]:
arquivo_bruto

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
arquivo_trabalhado = arquivo_bruto.iloc[0:5570, 1: ]
arquivo_trabalhado

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0

In [30]:
arquivo_trabalhado["DIFERENCA"] = arquivo_trabalhado["População Censo 2022"] - arquivo_trabalhado["População 2010 (Alterações de Limites até 2022)1"]

In [31]:
arquivo_trabalhado

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,DIFERENCA
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1395.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,245222.0

In [32]:
arquivo_trabalhado.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'DIFERENCA'],
      dtype='str')

In [ ]:
estado = ( arquivo_trabalhado.groupby("UF")[["População Municipio 2010\n(sinopse)",
          'População Censo 2022','Diferença']]
.sum()
.reset_index()
)